allow passport access using best matched url prefix
melnikk/oauth2_proxy pull request #4
Opened 2018-05-22 16:01 UTC by xxbbxb

Добавил авторизацию запросов на основе префикса адреса, т.е. теперь auth.yml разграничивать доступ в зависимости от пути, например так:
```
site.domain/team1/kibana:
- group1
site.domain/team2/kibana:
- group2
```
Фича очень спорная, но нам в проекте очень нужна. При таких проверках есть понятная проблема: аутентификационная куки устанавливается на домен, но знания домена недостаточно, чтобы управлять доступом к префиксу. У прокси нет возможности в любой момент обратиться к паспорту и запросить группы пользователя, потому что это можно делать только при наличие access_token, который доступен только в момент аутентификации и не хранится на протяжении всей сессии, проблему можно было решить:
1. через refresh_token и RefreshSessionIfNeeded, но требуется включение поддержки offline_access в паспорте;
2. Трюками через флаги конфигурации pass-access-token и cookie-refresh, тогда токен был бы всегда доступен, т.к. хранился бы в зашифрованном виде в куки;
3. Кэшировать группы в памяти процесса, а при рестарте прокси удалять авторизационную куки и заставлять пользователя проходить повторную авторизацию
Был выбран п. 3

2018-05-23 07:02 UTC, beevee requested changes
Я не хочу это ревьюить, потому что тут тонна правок, которые не относятся к префиксам урлов.

2018-05-23 07:02 UTC, beevee commented on main.go
> +	flagSet.String("passport-allowed-groups-file", "", "authentication file (yaml) with allowed url prefixes and groups")
Как это относится к префиксам урлов?

2018-05-23 07:02 UTC, beevee commented on options.go
> +	PassportAllowedGroupsFile string   `flag:"passport-allowed-groups-file" cfg:"passport_allowed_groups_file" env:"AUTH_FILE"`
Как это относится к префиксам урлов?

2018-05-23 07:02 UTC, beevee commented on options.go
> +			fmt.Println("using of environment variable AUTH_FILE is deprecated")
Почему deprecated? Как это относится к префиксам урлов?

2018-05-23 07:02 UTC, beevee commented on providers/passport.go
> +	auth                      unsafe.Pointer
О боже, unsafe pointer! А это как относится к префиксам урлов?

2018-05-24 08:32 UTC, beevee requested changes

2018-05-24 08:32 UTC, beevee commented on providers/passport.go
> +			p.userGroupsStore[email] = groups
Меня беспокоит, что тут будет конкурентный доступ к словарю. Надо взять потокобезопасный словарь или какой-нибудь нормальный кэш типа этого: https://github.com/patrickmn/go-cache

Почему нельзя без этого обойтись в многопоточной обработке: https://golang.org/doc/faq#atomic_maps

2018-05-25 05:23 UTC, xxbbxb commented on providers/passport.go
> +			p.userGroupsStore[email] = groups
Поправил

2018-05-25 07:43 UTC, merged